### ISSUE TITLE
Lexing fails at incorrect input.

### ISSUE THREAD

**Issue by wilbdhm** [wilbdhm/logicsolver#4]
$ java -cp build mbbm.logic.solver.Main '1 <=> ~0' '34'
    <TRUE> <EQUIV> <NOT> <FALSE> 
    Exception in thread "main" java.lang.IllegalStateException: No match found
            at java.base/java.util.regex.Matcher.group(Matcher.java:645)
            at mbbm.logic.solver.Lexer.lex(Lexer.java:24)
            at mbbm.logic.solver.Main.main(Main.java:10)

**Comment by wilbdhm** [comment]
Fixed in ccd06a53d78a9b710bdacba4dc388042a6f82435.

    $ java -cp build mbbm.logic.solver.Main '0 <=>~1' '34' 'abec   adło' '  KONŃ  ' '  &&!'
    <FALSE> <EQUIV> <NOT> <TRUE> 
    Unknown token: 34
    
    Unknown token: ło
    
    Unknown token: KONŃ
    
    Unknown token: !
